// src/routes/projects/+page.svelte
<script lang="ts">
	import { useFluidContext } from '$lib/context/fluid.svelte';
	import { onMount, tick } from 'svelte';
	import { routes } from '$lib/data/routes';
	import { project_ids } from '$lib/data/projects';
	import ProjectCard from './project-card.svelte';

	const fluid = useFluidContext();

	let behavior: ScrollBehavior = $state('instant');
	let activeIndex: number = $state(0);
	let carouselEl: HTMLUListElement;
	let scrollTimeout: ReturnType<typeof setTimeout>;

	function updateActiveState() {
		if (!carouselEl) return;

		const containerCenter = carouselEl.scrollLeft + carouselEl.offsetWidth / 2;

		let i = 0;

		for (const child of Array.from(carouselEl.children)) {
			if (child.tagName === 'LI') {
				const card = child as HTMLLIElement;
				const cardCenter = card.offsetLeft - 128.5 + card.offsetWidth / 2;
				const distance = Math.abs(containerCenter - cardCenter);

				if (distance == 0) {
					activeIndex = i;
					sessionStorage.setItem('carousel_index', i.toString());
					return;
				}
				i += 1;
			}
		}
	}

	function scroll(direction: -1 | 1, wrap = true) {
		if (wrap) {
			activeIndex = (project_ids.length + activeIndex + direction) % project_ids.length;
		} else {
			activeIndex = Math.max(0, Math.min(activeIndex + direction, project_ids.length - 1));
		}
		sessionStorage.setItem('carousel_index', activeIndex.toString());
	}

	onMount(() => {
		fluid.registerText('');
		fluid.changeColor(routes[2].color);

		activeIndex = Number(sessionStorage.getItem('carousel_index'));
		const controller = new AbortController();

		window.addEventListener(
			'wheel',
			(e: WheelEvent) => {
				scroll(0 < e.deltaY ? 1 : -1, false);
			},
			{ passive: true, signal: controller.signal }
		);
		window.addEventListener(
			'scroll',
			() => {
				clearTimeout(scrollTimeout);
				scrollTimeout = setTimeout(updateActiveState, 50);
			},
			{
				passive: true,
				signal: controller.signal,
				capture: true
			}
		);

		tick().then(() => (behavior = 'smooth'));

		return () => {
			controller.abort();
			clearTimeout(scrollTimeout);
		};
	});
</script>

<svelte:head>
	<title>Projects - LiamS-H</title>
</svelte:head>

<div class="relative h-full flex flex-col justify-center px-10 md:px-32">
	<button
		class="absolute left-4 top-1/2 lg:top-2/3 lg:-translate-x-14 lg:left-1/2 z-10 -translate-y-1/2 text-white/50 transition-colors hover:text-white"
		onclick={() => scroll(-1)}
		aria-label="Scroll left"
	>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			class="h-12 w-12"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			stroke-width="1.5"
		>
			<path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
		</svg>
	</button>
	<div class="flex flex-col-reverse justify-center">
		<ul
			bind:this={carouselEl}
			class="h-fit gap-8 md:gap-24 flex flex-row items-center overflow-x-auto snap-x snap-mandatory md:snap-normal
                    mask-[linear-gradient(to_right,transparent,black_20%,black_80%,transparent)]
                    [webkit-mask:linear-gradient(to_right,transparent,black_20%,black_80%,transparent)]"
			style="scrollbar-width: none;"
		>
			<div class="min-w-[40%] h-full"></div>
			{#each project_ids as id, i}
				<ProjectCard {id} active={activeIndex === i} {behavior} />
			{/each}
			<div class="min-w-[40%] h-full"></div>
		</ul>
	</div>
	<button
		class="absolute right-4 top-1/2 z-10 lg:top-2/3 lg:left-1/2 -translate-y-1/2 text-white/50 transition-colors hover:text-white"
		onclick={() => scroll(1)}
		aria-label="Scroll right"
	>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			class="h-12 w-12"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			stroke-width="1.5"
		>
			<path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
		</svg>
	</button>
</div>

// src/routes/Projects/index.tsx
import { useEffect, useRef, useState } from "react";

import { ArrowLeft, ArrowRight } from "lucide-react";
import { ScrycardsCard } from "./Scrycards";
import { FOOODCard } from "./FOOOD";
import { ConfluenceCard } from "./Confluence";
import { ShahrazadCard } from "./Shahrazad";

function debounce<F extends (...args: unknown[]) => unknown>(
    func: F,
    delay: number
) {
    let timeoutId: ReturnType<typeof setTimeout> | null = null;
    return function (this: unknown, ...args: Parameters<F>) {
        if (timeoutId !== null) {
            clearTimeout(timeoutId);
        }
        timeoutId = setTimeout(() => {
            func.apply(this, args);
        }, delay);
    };
}

export default function Projects() {
    const scrollable_ref = useRef<HTMLDivElement | null>(null);
    const [currentIndex, setCurrentIndex] = useState(0);
    const [totalChildren, setTotalChildren] = useState(0);

    useEffect(() => {
        const container = scrollable_ref.current;
        if (!container) return;

        const children = Array.from(container.children);
        setTotalChildren(children.length);

        const handleScroll = () => {
            const children = Array.from(container.children);
            let closestChild: Element | null = null;
            let minDistance = Infinity;
            let closestIndex = 0;
            const parentRect = container.getBoundingClientRect();

            for (let i = 1; i < children.length - 1; i++) {
                const child = children[i];
                const rect = child.getBoundingClientRect();
                const distance = Math.abs(
                    rect.left +
                        rect.width / 2 -
                        (parentRect.left + parentRect.width / 2)
                );

                if (distance < minDistance) {
                    minDistance = distance;
                    closestChild = child;
                    closestIndex = i;
                }
            }

            setCurrentIndex(closestIndex);

            if (closestChild) {
                closestChild.scrollIntoView({
                    behavior: "smooth",
                    block: "center",
                    inline: "center",
                });
            }
        };
        handleScroll();

        const debouncedHandleScroll = debounce(handleScroll, 50);

        container.addEventListener("scroll", debouncedHandleScroll);

        return () => {
            container.removeEventListener("scroll", debouncedHandleScroll);
        };
    }, []);

    const navigateProject = (direction: "left" | "right") => {
        const container = scrollable_ref.current;
        if (!container) return;

        const children = Array.from(container.children);
        const newIndex =
            direction === "left"
                ? Math.max(0, currentIndex - 1)
                : Math.min(totalChildren - 1, currentIndex + 1);

        setCurrentIndex(newIndex);

        children[newIndex].scrollIntoView({
            behavior: "smooth",
            block: "nearest",
            inline: "center",
        });
    };
    return (
        <div className="h-full px-16 md:px-32 flex flex-col justify-center">
            <div className="flex flex-col-reverse justify-center">
                <div className="flex w-full justify-center">
                    <div className="absolute left-4 top-1/2 transform md:static md:left-auto md:top-auto z-10">
                        <button
                            onClick={() => navigateProject("left")}
                            disabled={currentIndex === 1}
                            className=" p-2 rounded-full disabled:opacity-50"
                            aria-label="previous project"
                        >
                            <ArrowLeft />
                        </button>
                    </div>
                    <div className="absolute right-4 top-1/2 transform md:static md:left-auto md:top-auto z-10">
                        <button
                            onClick={() => navigateProject("right")}
                            disabled={currentIndex === totalChildren - 2}
                            className="p-2 rounded-full disabled:opacity-50"
                            aria-label="next project"
                        >
                            <ArrowRight />
                        </button>
                    </div>
                </div>

                <div
                    ref={scrollable_ref}
                    className="h-fit gap-8 md:gap-24 flex flex-row justify-around items-center overflow-x-auto relative
                    [mask-image:linear-gradient(to_right,transparent,black_20%,black_60%,transparent)] 
                    [webkit-mask:linear-gradient(to_right,transparent,black_20%,black_60%,transparent)]"
                    style={{
                        scrollbarWidth: "none",
                    }}
                >
                    <div className="min-w-[45%]" />

                    <ShahrazadCard scrollable_ref={scrollable_ref} />

                    <FOOODCard scrollable_ref={scrollable_ref} />

                    <ScrycardsCard scrollable_ref={scrollable_ref} />

                    <ConfluenceCard scrollable_ref={scrollable_ref} />

                    <div className="min-w-[45%]" />
                </div>
            </div>
        </div>
    );
}
