// src/routes/navbar.svelte
<script lang="ts">
	import { registerSolid } from '$lib/components/fluid/solid.svelte';

	const routes = [
		{ path: '/', label: 'Home', color: 0 },
		{ path: '/about', label: 'About', color: 1 },
		{ path: '/projects', label: 'Projects', color: 6 }
	];
</script>

<nav class="fixed bottom-0 w-full mb-20 md:mb-8 md:px-[20%]">
	<ul class="flex justify-around">
		{#each routes as route}
			<a href={`${route.path}`} data-sveltekit-preload-data="hover">
				<div
					class={`text-transparent bg-clip-text bg-color-1 animate-gradient-swirl p-4`}
					use:registerSolid={{ id: `nav-${route.path}`, color: route.color, inner: 4 }}
				>
					<span>
						{route.label}
					</span>
				</div>
			</a>
		{/each}
	</ul>
</nav>

// src/navbar.tsx
import { NavLink, useLocation } from "react-router-dom";
import { routes } from "./routes";
import Hitbox from "./components/hitbox";

function NavBarButton(props: { path: string; label: string; active: boolean }) {
    return (
        <NavLink
            to={props.path}
            className={props.active ? "cursor-default" : undefined}
        >
            <Hitbox
                id={props.path}
                className={`bg-black p-4 mb-4 ${
                    props.active
                        ? " text-purple-600"
                        : " text-white hover:text-pink-500"
                }`}
            >
                <li key={props.path}>{props.label}</li>
            </Hitbox>
        </NavLink>
    );
}

export default function NavBar() {
    const { pathname } = useLocation();
    return (
        <nav className="fixed bottom-0 w-full md:px-[20%]">
            <ul className="flex justify-around">
                {routes.map((r) => (
                    <NavBarButton
                        key={r.path}
                        path={r.path}
                        label={r.label}
                        active={pathname === r.path}
                    />
                ))}
            </ul>
        </nav>
    );
}
